#!/usr/bin/env python3
import sys
import json
import requests
from publicbroadcasterapi import Zdf3SatApi

API_TOKEN_PREFIX = 'Bearer'
ENDPOINT = {
	'apiTokenUri': 'https://zdf-cdn.live.cellular.de/mediathekV2/token',
	'apiUrl': 'https://api.3sat.de',
	'apiPath': 'content/documents/zdf',
	'apiParams': '?profile=player'
}

def token3Sat(url):
	api = None
	print('Fetch URL: ', url)
	r = requests.get(url)
	if r.status_code == 200:
		cnt = r.text
		startPosition = cnt.find('data-zdfplayer-jsb')
		if startPosition > -1:
				endPosition = cnt.find('}', cnt.find('data-zdfplayer-jsb'))
				if endPosition > -1:
						jc = cnt[startPosition+20:endPosition+1]
						try:
								jc = json.loads(jc.replace('\n', ''))
								api = '%s %s' % (API_TOKEN_PREFIX, jc['apiToken'])
						except:
								pass

	if api is None:
		sys.stderr.write('Could not retrieve the API token!')
	else:
		print('Found API: %s' % (api,))
		return api

if __name__ == '__main__':
	playUrl = False
	if len(sys.argv) > 2:
		if sys.argv[1] == '--play':
			playUrl = True
			url = sys.argv[2]
		else:
			url = sys.argv[1]
	elif len(sys.argv) > 1:
		url = sys.argv[1]
	else:
		url = input('Give me the URL: ')

	media = Zdf3SatApi(ENDPOINT, fallbackToken=token3Sat)
	streams = media.fetchStream(url)
	if playUrl:
		media.printStreams(streams, True)
	else:
		print('\nStreams: ')
		media.printStreams(streams)
