#!/bin/sh
DOCID=$1
echo $DOCID
vlc `curl "https://classic.ardmediathek.de/play/media/$DOCID?devicetype=pc&features=hls" | json_reformat | grep -A5 '"_quality": 3,' | grep '_stream' | awk -F'"' '{ print $4 }'`
