#!/usr/bin/env python3
import sys
from broadcast.ard import ArdApi

if __name__ == '__main__':
	playUrl = False
	if len(sys.argv) > 2:
		if sys.argv[1] == '--play':
			playUrl = True
			url = sys.argv[2]
		else:
			url = sys.argv[1]
	elif len(sys.argv) > 1:
		url = sys.argv[1]
	else:
		url = input('Give me the URL: ')

	media = ArdApi()
	streams = media.fetchStream(url)
	if playUrl:
		media.printStreams(streams, True)
	else:
		media.printStreams(streams)
