#!/usr/bin/env python3
import sys
from broadcast.zdf3sat import Zdf3SatApi

ENDPOINT = {
	'apiTokenUri': 'https://zdf-cdn.live.cellular.de/mediathekV2/token',
	'apiUrl': 'https://api.zdf.de',
	'apiPath': 'content/documents/zdf',
	'apiParams': '?profile=player'
}

if __name__ == '__main__':
	playUrl = False
	if len(sys.argv) > 2:
		if sys.argv[1] == '--play':
			playUrl = True
			url = sys.argv[2]
		else:
			url = sys.argv[1]
	elif len(sys.argv) > 1:
		url = sys.argv[1]
	else:
		url = input('Give me the URL: ')

	media = Zdf3SatApi(ENDPOINT)
	streams = media.fetchStream(url)
	if playUrl:
		media.printStreams(streams, True)
	else:
		print('\nStreams: ')
		media.printStreams(streams)
